CC = gcc
OPTIONS = -Wall -ansi -pedantic
all: exercice1 exercice2
exercice1: exercice1.c
	$(CC) $(OPTIONS) exercice1.c -o exercice1
exercice2: exercice2.c
	$(CC) $(OPTIONS) exercice2.c -o exercice2
exercice3: exercice3.c
	$(CC) $(OPTIONS) exercice3.c -o exercice3
exercice4: exercice4.c
	$(CC) $(OPTIONS) exercice4.c -o exercice4